In [2]:
import pandas as pd
import statsmodels.api as sm

from statsmodels.discrete.count_model import ZeroInflatedPoisson


df = pd.read_csv("/content/ndtv_data_final.csv")
df

,Unnamed: 0,Name,Brand,Model,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,...,Rear camera,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price
0,0,OnePlus 7T Pro McLaren Edition,OnePlus,7T Pro McLaren Edition,4085,6.67,Yes,1440,3120,8,...,48.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,58998
1,1,Realme X2 Pro,Realme,X2 Pro,4000,6.50,Yes,1080,2400,8,...,64.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,27999
2,2,iPhone 11 Pro Max,Apple,iPhone 11 Pro Max,3969,6.50,Yes,1242,2688,6,...,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,106900
3,3,iPhone 11,Apple,iPhone 11,3110,6.10,Yes,828,1792,6,...,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,62900
4,4,LG G8X ThinQ,LG,G8X ThinQ,4000,6.40,Yes,1080,2340,8,...,12.0,32.0,Android,Yes,Yes,Yes,1,No,No,49990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1354,1354,Intex Aqua A2,Intex,Aqua A2,1500,4.00,Yes,480,800,4,...,5.0,0.3,Android,Yes,Yes,Yes,2,Yes,No,2599
1355,1355,Videocon Infinium Z51 Nova+,Videocon,Infinium Z51 Nova+,2000,5.00,Yes,480,854,4,...,8.0,5.0,Android,Yes,Yes,Yes,2,Yes,No,2940
1356,1356,Intex Aqua Y4,Intex,Aqua Y4,1700,4.50,Yes,480,854,2,...,5.0,2.0,Android,Yes,Yes,No,2,Yes,No,2999
1357,1357,iBall Andi4 B20,iBall,Andi4 B20,1250,4.00,Yes,480,800,1,...,2.0,0.3,Android,Yes,Yes,Yes,2,Yes,No,2498
1358,1358,iBall Andi Avonte 5,iBall,Andi Avonte 5,2150,5.00,Yes,480,854,4,...,8.0,0.0,Android,Yes,Yes,Yes,2,Yes,No,3999

In [3]:

X = df[["Brand","Model"]]
X

         Brand                   Model
0      OnePlus  7T Pro McLaren Edition
1       Realme                  X2 Pro
2        Apple       iPhone 11 Pro Max
3        Apple               iPhone 11
4           LG               G8X ThinQ
...        ...                     ...
1354     Intex                 Aqua A2
1355  Videocon      Infinium Z51 Nova+
1356     Intex                 Aqua Y4
1357     iBall               Andi4 B20
1358     iBall           Andi Avonte 5

[1359 rows x 2 columns]

In [6]:
y = df["Processor"]
y

0       8
1       8
2       6
3       6
4       8
       ..
1354    4
1355    4
1356    2
1357    1
1358    4
Name: Processor, Length: 1359, dtype: int64

In [7]:

X = sm.add_constant(X)
X

      const     Brand                   Model
0       1.0   OnePlus  7T Pro McLaren Edition
1       1.0    Realme                  X2 Pro
2       1.0     Apple       iPhone 11 Pro Max
3       1.0     Apple               iPhone 11
4       1.0        LG               G8X ThinQ
...     ...       ...                     ...
1354    1.0     Intex                 Aqua A2
1355    1.0  Videocon      Infinium Z51 Nova+
1356    1.0     Intex                 Aqua Y4
1357    1.0     iBall               Andi4 B20
1358    1.0     iBall           Andi Avonte 5

[1359 rows x 3 columns]

In [11]:
print(X.select_dtypes(include="object").columns)

Index(['Brand', 'Model'], dtype='object')

In [15]:
X = pd.get_dummies(X, drop_first=True)

In [17]:

print(df["Processor"].value_counts())

Processor
4     683
8     565
2      45
1      42
6      20
10      4
Name: count, dtype: int64

In [19]:

zero_percentage = (df["Processor"] == 0).mean() * 100

print("Zero Percentage:", round(zero_percentage,2), "%")

Zero Percentage: 0.0 %

In [ ]:

age = int(input("Enter Brand: "))
bmi = float(input("Enter Model: "))

new_data = pd.DataFrame({
    "const": [1],
    "Model": [Model],
    "Brand": [Brand]
})

prediction = result.predict(
    exog=new_data,
    exog_infl=new_data
)

print("Predicted Children:", round(prediction[0]))